	
maximum: maximum.c driver.c driver.h total.c
	gcc -D MAXIMUM maximum.c driver.c total.c -o maximum
	
median: median.c driver.c driver.h total.c
	gcc -D MEDIAN median.c driver.c total.c -o median
		
clean:
	rm -f *.o maximum median